fix publish when mount pod deleted delay
juicedata/juicefs-csi-driver pull request #240
Opened 2021-12-30 09:45 UTC by zwwhdls

fix https://github.com/juicedata/juicefs-csi-driver/issues/239

Check if mount pod deleted when adding ref in annotation. If deleting, return err.

2021-12-31 00:06 UTC, yujunz requested changes
Typo?

2021-12-31 00:06 UTC, yujunz commented on pkg/juicefs/mount/pod_mount.go
> +			return status.Errorf(codes.Internal, "addRefOfMount: Mount pod [%s] has been deletes.", podName)
```suggestion
			return status.Errorf(codes.Internal, "addRefOfMount: Mount pod [%s] has been deleted.", podName)
```

2021-12-31 07:12 UTC, zwwhdls commented on pkg/juicefs/mount/pod_mount.go
> +			return status.Errorf(codes.Internal, "addRefOfMount: Mount pod [%s] has been deletes.", podName)
yes, typo...

2022-01-05 10:17 UTC, davies approved these changes

2022-01-05 10:17 UTC, merged