first cut of sidecar docs
juicedata/juicefs-csi-driver pull request #560
Opened 2023-02-10 04:00 UTC by timfeirg

2023-02-10 07:04 UTC, timfeirg commented
will add some more docs regarding pv

2023-02-10 07:39 UTC, timfeirg commented
will add helm tutorial, will explain installation method differences

2023-02-13 05:09 UTC, zwwhdls requested changes

2023-02-13 05:09 UTC, zwwhdls commented on docs/zh_cn/getting_started.md
> +./juicefs-csi-webhook-install.sh > juicefs-csi-sidecar.yaml
两种方式：

1. 直接安装
```
./juicefs-csi-webhook-install.sh install
```

2. 生成 安装 yaml 后再安装
```
./juicefs-csi-webhook-install.sh print > juicefs-csi-sidecar.yaml
kubectl apply -f ./juicefs-csi-sidecar.yaml
```

2023-02-13 07:53 UTC, zwwhdls approved these changes

2023-02-13 09:14 UTC, xiaogaozi approved these changes

2023-02-13 09:16 UTC, merged